{
 "title": "redpill view",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "read log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT rs.read_url,ts.name,rs.create_time from rlogs rs,l2tags ls , tags ts \r\nwhere rs.id = ls.log and ls.tag = ts.id limit 200"
    }
   ]
  },
  {
   "title": "state of mind",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT ts.type,count(ts.id) as s from l2tags ls,tags ts \r\nwhere ls.tag = ts.id group by type order by s desc;"
    }
   ]
  },
  {
   "title": "top 20",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT ts.name,count(ts.id) as s from l2tags ls,tags ts \r\nwhere ls.tag = ts.id group by name order by s desc limit 20;"
    }
   ]
  },
  {
   "title": "alert",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  3111 as negative, 211 as positive;"
    }
   ]
  }
 ]
}